//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XM_books.EF_Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_books
    {
        public System.Guid id_uniq { get; set; }
        public string nazvanie { get; set; }
        public string autor { get; set; }
        public short year_print { get; set; }
        public short id_junr { get; set; }
    }
}
