//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XM_books.EF_Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_books6
    {
        public Nullable<long> nn { get; set; }
        public string nazvanie { get; set; }
        public string autor { get; set; }
        public short PublicYear { get; set; }
        public string name_junr { get; set; }
        public short id_junr { get; set; }
        public System.Guid id_book { get; set; }
    }
}
