//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XM_books.EF_Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_junrs_for_menu2
    {
        public short id_value { get; set; }
        public string nazvanie { get; set; }
    }
}
